### ISSUE TITLE
Proposal/epic: Rename "docker-py" to "Docker SDK for Python"

### ISSUE THREAD

**Issue by bfirsh** [docker/docker-py#1310]
### Proposal

As part of a wider initiative, we're creating some properly supported SDKs for the Engine API.

docker-py was the first official-ish library, all that time ago. [Go is now the second](https://godoc.org/github.com/docker/docker/client). However, if we're going to continue to create ones for other languages, it'd be nice if they had consistent naming, roughly consistent APIs, and so on. It is also helpful to be able to refer them as a collective product, rather than the wishy-washy "client libraries for the Engine API".

Hence, the "Docker SDKs". Each particular language will be "Docker SDK for X": Docker SDK for Python, Docker SDK for Go, etc. [There will be centralised documentation](https://github.com/docker/docker.github.io/pull/210) with [a getting started guide for multiple languages (and curl!)](https://raw.githubusercontent.com/bfirsh/docker.github.io/21c4a7407f4782bc6337213fb8fa2bc2253163d2/api/getting-started.md), then linking off to each library's respective reference documentation.

### Tasks

- [ ] Make it really clear that "docker-py" is now "Docker SDK for Python". All old URLs should redirect, all landing pages should mention that it has renamed, and so on.
- [ ] Replace all mentions of "docker-py" in the source code with "Docker SDK for Python" or "docker-sdk-python".
- [ ] Move the GitHub repository to docker/docker-sdk-python. (Update Travis, Jenkins, etc, too.)
- [ ] Move the documentation to https://docker-sdk-python.readthedocs.io. Ensure the old documentation redirects correctly.
- [ ] Release 2.0 as the PyPi package "docker", not "docker-py". "docker-py" will remain for 1.x.
